---
title: "CS50P Harvard Course"
format: html
---

# Computer Science with Python

I am surprised that the theme littlebits doesn't highlight correctly qmd files... I must change the theme right now.

## Python Introduction--Lecture 0

### VS Code Editor

VS Code is a text editor that has a **compiler**. At the top, you'll notice a text editor. At the bottom, there's a terminal where commands are executed. In the terminal, you can execute `code hello.py`  to start coding. In the text editor above, you can type `print("hello, world")`. This the program that all coders write while learning to program.

In the terminal window, you can execute commands. To run this program, you are going to need to move your cursor to the bottom of the screen, clicking in the terminal window. You can now type a second command in the terminal window. Next to the dollar sign, type `python hello.py` and press the enter key on your keyboard.

When you run `python hello.py`, python will interpret the text that you created in hello.py and translate it into the zeros and ones that the computer can understand.
The result of running the `python hello.py` program is `hello, world`.
Congrats! You just created your first program.

How I actually do it: There's atriangle facing to the right with a bug.  Press it with the .py program open and you'll be fine.  This corresponds to Run and Debug and it works fine.

### Functions

The material took the `print("args")` function with some arguments ("args") to show what it does: It just prints on the console or terminal. I guess more on functions later...

### Bugs

Errors in the program... Nothing to see here... A parenthesis not closed a syntax error... This is part of the process and debugging the program is a must.

### First Program: "Hello World!"

```{python}

print("Hello world!")
```

#### Variables

#### Comments

#### Pseudocode

### First program improvements

### Strings and parameters

### Strings formating

### Integers

### Readability

### Floats

### Def (functions)

### Returning values

## Summary
